DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS (ID LONG AUTO_INCREMENT PRIMARY KEY, NUMERODEMATRICULA INT NOT NULL, NOMBRE VARCHAR(20) NOT NULL, APELLIDO VARCHAR(20) NOT NULL);

INSERT INTO ODONTOLOGOS (NUMERODEMATRICULA, NOMBRE, APELLIDO) VALUES (222, 'Carlos', 'Lopez'), (223,'Luis', 'Roma');